[tool.poetry]
name = "tabatatimer"
version = "0.1.0"
description = ""
authors = ["Krytos <kmeinon@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
nicegui = "^1.2.23"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
